version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_router
    ports:
      - "30002:30002"  # Expose port 30002 for example1.com and example2.com
      - "7050:7050"    # Expose port 7050 for example3.com
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount custom NGINX config
    networks:
      - custom_network
    depends_on:
      - example1
      - example2
      - example3

  example1:
    image: httpd:latest  # Replace with actual image for example1.com
    container_name: example1
    networks:
      - custom_network

  example2:
    image: httpd:latest  # Replace with actual image for example2.com
    container_name: example2
    networks:
      - custom_network

  example3:
    image: httpd:latest  # Replace with actual image for example3.com
    container_name: example3
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
